name: EAS Build Android

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: Install project dependencies
        run: npm install

<<<<<<< HEAD
      - name: Patch deprecated compile() in firebase analytics
        run: |
          sed -i -E "s/\bcompile\b/implementation/g" node_modules/react-native-firebase-analytics/android/build.gradle
=======
      - name: Fix deprecated compile() in build.gradle
        run: |
          # Fix deprecated compile to implementation in react-native-firebase-analytics build.gradle
          sed -i 's/compile(/implementation(/g' node_modules/react-native-firebase-analytics/android/build.gradle
          echo "Fixed deprecated compile() to implementation() in build.gradle"
>>>>>>> 403723e (feat: add EAS build config and GitHub Actions workflow)

      - name: Initialize EAS Project
        run: eas init --non-interactive --id c24319d4-689b-4401-8941-1d62827e6c81
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Run EAS Build
        run: eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
